

from tkinter import *

score2 = {}
def Logic():
    def first_quiz():
        first = Tk()
        first.geometry('600x400')
        first.title('Quiz app')
        first.resizable(width=False, height=False)
        def next1_func():
            global score2
            score2['1'] = var.get()
            first.destroy()
            second_quiz()
        label_top = Label(first, bg='green', width=90, height=2, fg='white',text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        label_top.pack()
        var = StringVar()
        var.set(0)
        quiz1 = Label(first, text='Darahta 10 qush otiripdi ovchi 2 tasini otib tushirdi nechta qush qoldi ?',font=('Arial', 15, 'bold'))
        quiz1.place(x=70, y=100)
        radio1 = Radiobutton(first, text='bitayam qolmadi', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radio1.place(x=70, y=140)
        radio2 = Radiobutton(first, text='15', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radio2.place(x=70, y=180)
        radio3 = Radiobutton(first, text='12', value="False", variable=var, font=('Arial', 15, 'normal'))
        radio3.place(x=70, y=220)
        radio4 = Radiobutton(first, text='5', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radio4.place(x=70, y=260)
        next = Button(first, text='Next', bg='blue', fg='white', width=13, height=2, command=next1_func)
        next.place(x=260, y=330)
        first.mainloop()
        
    def second_quiz():
        second = Tk()
        second.geometry('600x400')
        second.title('Quiz app')
        second.resizable(width=False, height=False)
        def next2_func():
            global score2
            score2['2'] = var.get()
            second.destroy()
            third_quiz()
        labell_top = Label(second, bg='green', width=90, height=2, fg='white',text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(second, text='suvda qanaqa tosh bolmaydi ? ',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(second, text='qizl', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(second, text='yashil', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(second, text='oq', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(second, text='quruq', value="Tog'ri", variable=var, font=(
    'Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(second, text='Next', bg='blue', fg='white', width=13, height=2, command=next2_func)
        nextt.place(x=260, y=330)
        second.mainloop()
    def third_quiz():
        third = Tk()
        third.geometry('600x400')
        third.title('Quiz app')
        third.resizable(width=False, height=False)
        def next3_func():
            global score2
            score2['2'] = var.get()
            third.destroy()
            fourth_quiz()
        labell_top = Label(third, bg='green', width=90, height=2, fg='white',text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(third, text='sigir nimaga yotadi ?',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(third, text='zerkanda', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(third, text='bo"kib qolganda', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(third, text='qorni och ganda ', value="Error", variable=var, font=('Arial', 15,'normal', ))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(third, text='chunki o"tirishni bilmidi', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(third, text='Next', bg='blue', fg='white', width=13, height=2, command=next3_func)
        nextt.place(x=260, y=330)
        third.mainloop()
    def fourth_quiz():
        fourth = Tk()
        fourth.geometry('600x400')
        fourth.title('Quiz app')
        fourth.resizable(width=False, height=False)
        def next4_func():
            global score2
            score2['4'] = var.get()
            fourth.destroy()
            fiveth_quiz()
        labell_top = Label(fourth, bg='green', width=90, height=2, fg='white',
            text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(fourth, text='1 kg tosh og"irmi yokiy 1 kg pahtami?',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(fourth, text='tosh', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(fourth, text='bilmiman', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(fourth, text='pahta', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(fourth, text='ikalasi teng', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(fourth, text='Next', bg='blue', fg='white', width=13, height=2, command=next4_func)
        nextt.place(x=260, y=330)
        fourth.mainloop()
    def fiveth_quiz():
        fiveth = Tk()
        fiveth.geometry('600x400')
        fiveth.title('Quiz app')
        fiveth.resizable(width=False, height=False)
        def next5_func():
            global score2
            score2['5'] = var.get()
            fiveth.destroy()
            sixth_quiz()
        labell_top = Label(fiveth, bg='green', width=90, height=2, fg='white',text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(fiveth, text='[roq] sozini teskarisi ?  ',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(fiveth, text='qor', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(fiveth, text='roq', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(fiveth, text='orq', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(fiveth, text='qo', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(fiveth, text='Next', bg='blue', fg='white', width=13, height=2, command=next5_func)
        nextt.place(x=260, y=330)
        fiveth.mainloop()
    def sixth_quiz():
        sixth = Tk()
        sixth.geometry('600x400')
        sixth.title('Quiz app')
        sixth.resizable(width=False, height=False)
        def next6_func():
            global score2
            score2['6'] = var.get()
            sixth.destroy()
            seventh_quiz()
        labell_top = Label(sixth, bg='green', width=90, height=2, fg='white', text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(sixth, text='a+a+a=6 | b+b+a=10 | s+s+b=10 | s+b+a= ?',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(sixth, text='9', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(sixth, text='10', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(sixth, text='7', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(sixth, text='5', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(sixth, text='Next', bg='blue', fg='white', width=13, height=2, command=next6_func)
        nextt.place(x=260, y=330)
        sixth.mainloop()
    def seventh_quiz():
        seventh = Tk()
        seventh.geometry('600x400')
        seventh.title('Quiz app')
        seventh.resizable(width=False, height=False)
        def next7_func():
            global score2
            score2['7'] = var.get()
            seventh.destroy()
            eightth_quiz()
        labell_top = Label(seventh, bg='green', width=90, height=2, fg='white',text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(seventh, text='2+2*2',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(seventh, text='4', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(seventh, text='9', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(seventh, text='15', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(seventh, text='6', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(seventh, text='Next', bg='blue', fg='white', width=13, height=2, command=next7_func)
        nextt.place(x=260, y=330)
        seventh.mainloop() 
    def eightth_quiz():
        eightth = Tk()
        eightth.geometry('600x400')
        eightth.title('Quiz app')
        eightth.resizable(width=False, height=False)
        def next8_func():
            global score2
            score2['8'] = var.get()
            eightth.destroy()
            nineth_quiz()
        labell_top = Label(eightth, bg='green', width=90, height=2, fg='white', text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(eightth, text='fil bilan sichqon urishsa kim yutadi ?',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(eightth, text='hechkim', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(eightth, text='fil', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(eightth, text='bilmasam', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(eightth, text='sichqon', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(eightth, text='Next', bg='blue', fg='white', width=13, height=2, command=next8_func)
        nextt.place(x=260, y=330)
        eightth.mainloop()
    def nineth_quiz():
        nineth = Tk()
        nineth.geometry('600x400')
        nineth.title('Quiz app')
        nineth.resizable(width=False, height=False)
        def next9_func():
            global score2
            score2['9'] = var.get()
            nineth.destroy()
            tenth_quiz()
        labell_top = Label(nineth, bg='green', width=90, height=2, fg='white',text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(nineth, text='bog"irso chomilip chiqiptide voy dipti"boshi yuvish esdan chiqiptiyu" diyarmush ?',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(nineth, text='nma?', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(nineth, text='hahaha', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(nineth, text='qanaqilib', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(nineth, text='chunmadim', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(nineth, text='Next', bg='blue', fg='white', width=13, height=2, command=next9_func)
        nextt.place(x=260, y=330)
        nineth.mainloop()
    def tenth_quiz():
        tenth = Tk()
        tenth.geometry('600x400')
        tenth.title('Quiz app')
        tenth.resizable(width=False, height=False)
        def next10_func():
            global score2
            score2['10'] = var.get()
            print(score2)
            tenth.destroy()
                   
        labell_top = Label(tenth, bg='green', width=90, height=2, fg='white',text='Quiz app by G11 group', font=('Arial', 15, 'normal'))
        labell_top.pack()
        var = StringVar()
        var.set(0)
        quizz1 = Label(tenth, text='1+1=?',font=('Arial', 15, 'bold'))
        quizz1.place(x=70, y=100)
        radioo1 = Radiobutton(tenth, text='2', value="Tog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo1.place(x=70, y=140)
        radioo2 = Radiobutton(tenth, text='13', value="Notog'ri", variable=var, font=('Arial', 15, 'normal'))
        radioo2.place(x=70, y=180)
        radioo3 = Radiobutton(tenth, text='10', value="False", variable=var, font=('Arial', 15, 'normal'))
        radioo3.place(x=70, y=220)
        radioo4 = Radiobutton(tenth, text='5', value="Error", variable=var, font=('Arial', 15, 'normal'))
        radioo4.place(x=70, y=260)
        nextt = Button(tenth, text='Next', bg='blue', fg='white', width=13, height=2, command=next10_func)
        nextt.place(x=260, y=330)
        tenth.mainloop()
        
    first_quiz()
